apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: xzv9skpot-dotnet-basic-gitops-repository
spec:
  url: https://github.com/tnevrlka-rhtap/xzv9skpot-dotnet-basic-gitops